# Generated by Django 4.2.2 on 2023-07-02 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
