# Generated by Django 4.2.2 on 2023-07-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0002_job_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
