# Generated by Django 4.2.2 on 2023-07-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_employer'),
        ('job_post', '0003_job_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weixin.employer'),
        ),
    ]
