# Generated by Django 4.2.2 on 2023-09-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0005_alter_job_jd'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='if_prioritize',
            field=models.CharField(choices=[('是', '是'), ('否', '否'), ('其他', '其他')], default='是', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='if_remote',
            field=models.CharField(choices=[('远程', '远程'), ('线下', '线下'), ('混合模式', '混合模式')], default='线下', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='if_training',
            field=models.CharField(choices=[('是', '是'), ('否', '否'), ('按需提供', '按需提供')], default='是', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('全职', '全职'), ('兼职', '兼职')], default='全职', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(choices=[('1000-3000', '1000-3000'), ('3000-5000', '3000-5000'), ('5000-10000', '5000-10000'), ('10000+', '10000+'), ('固定收入', '固定收入')], default='1000-3000', max_length=20),
        ),
    ]
