# Generated by Django 4.2.2 on 2023-06-18 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('视觉平面设计', '视觉平面设计'), ('UI/IX等网站/小程序设计', 'UI/IX等网站/小程序设计'), ('行政/项目运营管理', '行政/项目运营管理'), ('摄影摄像', '摄影摄像'), ('语言翻译类', '语言翻译类'), ('销售岗位', '销售岗位'), ('社交媒体内容撰写', '社交媒体内容撰写'), ('小视频编辑制作', '小视频编辑制作'), ('文字编辑整理', '文字编辑整理'), ('其他', '其他')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type_ps', models.CharField(max_length=100)),
                ('dim_0', models.IntegerField()),
                ('dim_1', models.IntegerField()),
                ('dim_2', models.IntegerField()),
                ('dim_3', models.IntegerField()),
                ('dim_4', models.IntegerField()),
                ('dim_5', models.IntegerField()),
                ('dim_6', models.IntegerField()),
                ('dim_7', models.IntegerField()),
                ('dim_8', models.IntegerField()),
                ('dim_9', models.IntegerField()),
                ('dim_10', models.IntegerField()),
                ('expect_salary', models.CharField(max_length=100)),
                ('advice', models.CharField(max_length=1000)),
                ('job_type', models.ManyToManyField(to='weixin.jobtype')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
